ADD file:920cf788d1ba88f76c97e41e03e4dc2f3005b08d65b5e9da9dd1cbe20a74459b in /
CMD ["bash"]
LABEL maintainer=Jupyter Project <jupyter@googlegroups.com>
ARG NB_USER=jovyan
ARG NB_UID=1000
ARG NB_GID=100
SHELL [/bin/bash -o pipefail -c]
USER root
ARG conda_version=4.10.1
ARG miniforge_patch_number=5
ARG miniforge_arch=x86_64
ARG miniforge_python=Mambaforge
ARG miniforge_version=4.10.1-5
ARG miniforge_installer=Mambaforge-4.10.1-5-Linux-x86_64.sh
ARG miniforge_checksum=069e151cae85ed4747721e938e7974aa00889a1ae87cff33ddbdde9530fc4c6d
ENV DEBIAN_FRONTEND=noninteractive
RUN |10 NB_USER=jovyan NB_UID=1000 NB_GID=100
ENV CONDA_DIR=/opt/conda SHELL=/bin/bash NB_USER=jovyan NB_UID=1000
ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/home/jovyan CONDA_VERSION=4.10.1 MINIFORGE_VERSION=4.10.1-5
COPY fix-permissions /usr/local/bin/fix-permissions # buildkit
RUN |10 NB_USER=jovyan NB_UID=1000 NB_GID=100
RUN |10 NB_USER=jovyan NB_UID=1000 NB_GID=100
RUN |10 NB_USER=jovyan NB_UID=1000 NB_GID=100
USER 1000
ARG PYTHON_VERSION=default
RUN |11 NB_USER=jovyan NB_UID=1000 NB_GID=100
WORKDIR /tmp
RUN |11 NB_USER=jovyan NB_UID=1000 NB_GID=100
RUN |11 NB_USER=jovyan NB_UID=1000 NB_GID=100
EXPOSE map[8888/tcp:{}]
ENTRYPOINT ["tini" "-g" "--"]
CMD ["start-notebook.sh"]
COPY start.sh start-notebook.sh start-singleuser.sh /usr/local/bin/
COPY jupyter_notebook_config.py /etc/jupyter/ # buildkit
USER root
RUN |11 NB_USER=jovyan NB_UID=1000 NB_GID=100
USER 1000
WORKDIR /home/jovyan
LABEL maintainer=Jupyter Project <jupyter@googlegroups.com>
USER root
RUN /bin/bash -o pipefail -c
RUN /bin/bash -o pipefail -c
USER 1000
LABEL maintainer=Jupyter Project <jupyter@googlegroups.com>
USER root
RUN /bin/bash -o pipefail -c
USER 1000
RUN /bin/bash -o pipefail -c
WORKDIR /tmp
RUN /bin/bash -o pipefail -c
ENV XDG_CACHE_HOME=/home/jovyan/.cache/
RUN /bin/bash -o pipefail -c
USER 1000
WORKDIR /home/jovyan
LABEL maintainer=Jupyter Project <jupyter@googlegroups.com>
SHELL [/bin/bash -o pipefail -c]
USER root
ARG julia_version=1.6.0
ARG julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585
RUN |2 julia_version=1.6.0 julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585 /bin/bash
ENV JULIA_DEPOT_PATH=/opt/julia JULIA_PKGDIR=/opt/julia JULIA_VERSION=1.6.0
WORKDIR /tmp
RUN |2 julia_version=1.6.0 julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585 /bin/bash
RUN |2 julia_version=1.6.0 julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585 /bin/bash
USER 1000
RUN |2 julia_version=1.6.0 julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585 /bin/bash
RUN |2 julia_version=1.6.0 julia_checksum=463b71dc70ca7094c0e0fd6d55d130051a7901e8dec5eb44d6002c57d1bd8585 /bin/bash
WORKDIR /home/jovyan
